name: South Africa 2016
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.1863406
  brandStrength: 0.6129848
  lightness: 0.9957842
  brandColors:
    - '#E7EBF1'
    - '#BCBEBE'
    - '#413A30'
    - '#FFAD14'
    - '#814200'
  rhythmicContrast: 0.9080944
typography_spectrum: 0.8988196
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2934233
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
